### ISSUE TITLE
Webmin STILL redirects to domain.com:10000 after login..

### ISSUE THREAD

**Issue by MacGyver27** [webmin/webmin#1135]
Hi, after some decent time of troubleshooting and looking into suggestions of #1049 and #1027 and #976 (and also https://sourceforge.net/p/webadmin/discussion/600155/thread/6eb89f60/?page=1&limit=25#8999) still cant fix that redirect problem...

visit -> admin.example.com -> logs into webmin -> redirected to: admin.example.com:10000 -> 404 page not found -> manually delete port -> successfully inside webmin web app
^^^ every time

I am using official Debian package.
Operating system: Debian Linux 10
Webmin version: 1.930
Authentic theme version: 19.40 (forced upgrade since I was not able to find `update-from-repo.sh script to perform update to the latest development version.. how do I do it BTW if using official Debian package?)

For the reverse proxy I am using popular traefik.
traefik:
```
#webmin
  [backends.webmin]
    [backends.webmin.servers.1]
      url = "http://127.0.0.1:10000"
      weight = 1

#webmin
  [frontends.webmin]
    backend = "webmin"
    entryPoints = ["http", "https"]
    passHostHeader = true
	[frontends.webmin.whiteList]
	  sourceRange = ["192.168.255.0/24", "10.8.0.0/24"]
	  useXForwardedFor = true
	[frontends.webmin.headers]
	  forceSTSHeader = true
	  STSSeconds = 315360000
	  STSIncludeSubdomains=true
	  STSPreload = true
    [frontends.webmin.routes.1]
      rule = "Host:admin.example.com"
```

webmin config:
```
relative_redir=0
passwd_mindex=4
product=webmin
real_os_version=10
mobile_theme=virtual-server-mobile
real_os_type=Debian Linux
tempdelete_days=7
passwd_cindex=2
find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
referers_none=0
log=1
referers=admin.example.com
md5pass=1
ld_env=LD_LIBRARY_PATH
theme=authentic-theme
passwd_uindex=0
passwd_pindex=1
passwd_file=/etc/shadow
os_type=debian-linux
lang=en.UTF-8
by_view=0
os_version=10
path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
webprefix=
webprefixnoredir=1
dateformat=dd/mon/yyyy
help_width=
showlogin=0
hostnamemode=0
nofeedbackcc=0
hostnamedisplay=admin.example.com
showhost=0
sysinfo=0
feedback_to=admin@example.com
help_height=
gotomodule=
gotoone=0
deftab=webmin
nomoduleup=
nohostname=0
notabs=0
nowebminup=
```

miniserv.conf
```
sockets=127.0.0.1
port=10000
listen=10000
trust_real_ip=1
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
cookiepath=
no_testing_cookie=0
ssl=0
ssl_redirect=0
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
ipv6=1
session=1
premodules=WebminCore
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
passdelay=1
login_script=/etc/webmin/login.pl
failed_script=/etc/webmin/failed.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
sudo=1
nolog=.*xhr.*
sessiononly=/server-manager/remote.cgi
preload=server-manager=server-manager/server-manager-lib-funcs.pl
mobile_preroot=virtual-server-mobile
mobile_prefixes=m. mobile.
preroot=authentic-theme
root=/usr/share/webmin
mimetypes=/usr/share/webmin/mime.types
server=MiniServ/1.930
error_handler_401=401.cgi
error_handler_403=403.cgi
error_handler_404=404.cgi
```

I am reverse-proxying multiple different apps on different environments and webmin is only one having this problem :/ Any directions will be much appreciated.

PS: Is there a way to upgrade to the latest development version when using official package? thx

**Comment by rostovtsev** [comment]
Hi, Michal.  

You need to take a look at `traefik.frontend.passHostHeader` option for your Traefik. The idea is to tell proxy not to pass the host line from the incoming request to the proxied host. In Apache it can be done using `ProxyPreserveHost` option setting to `Off`.

This issue has been discused earlier already, [read more](https://github.com/containous/traefik/issues/4341) here.

----

The update script `update-from-repo.sh` is located on Debian under `/usr/share/webmin` directory.

>  Is there a way to upgrade to the latest development version when using official package?

Yes, there is a way, just run the script mentioned above. The package manager though, might be complaining later (upon installing new version from the repo), that the files were modified.

**Comment by MacGyver27** [comment]
Hi,

Thanks for prompt response. I changed it to `passHostHeader = false` and now after login it redirects to `http://127.0.0.1:10000/`..

**Comment by rostovtsev** [comment]
How about adding `relative_redir=1` in `/etc/webmin/config`?

**Comment by MacGyver27** [comment]
no effect :/ (passHostHeader = false/true)

**Comment by rostovtsev** [comment]
Then simply **redirect 127.0.0.1:10000 to ${NeededHost}**. Check the manual for how to do it exactly.

I had no idea what Traefik was before your post.

----

Example:

~~~
- traefik.frontend.rule=Host:example.com
- traefik.frontend.redirect.regex=https://127.0.0.1:10000
- traefik.frontend.redirect.replacement=https://webmin.example.com
~~~

Check [this post](https://github.com/containous/traefik/issues/2796#issuecomment-412035522) out, might be helpful.

**Comment by MacGyver27** [comment]
Traefik is a simple reverse proxy gateway.. mainly it bundles all required features for clouding like letsencrypt, metrics and - mainly - it natively works with docker/kubernetes - so each container carries own config for reverse proxy and is only active when container is up.. another benefit compared to HA or NGINX is it couples those 2 worlds - "cloud" and "static" - together.. so you can have everything under single management. Yeah and also webUI is nice..

--

Based on `passHostHeader = false/true` I was trying to redirect either `127.0.0.1:10000` or `admin.example.com:10000` to `admin.example.com` without any effect. Was using example from different working endpoint :/ Both examples are using original webmin config I mention in the first post..

1)
```toml
#webmin
  [frontends.webmin]
    backend = "webmin"
    entryPoints = ["http", "https"]
    passHostHeader = true
	[frontends.webmin.whiteList]
	  sourceRange = ["192.168.255.0/24", "10.8.0.0/24"]
	  useXForwardedFor = true
	[frontends.webmin.headers]
	  forceSTSHeader = true
	  STSSeconds = 315360000
	  STSIncludeSubdomains=true
	  STSPreload = true
    [frontends.webmin.redirect]
  	  regex = "^https?://admin.example.com:10000/(.*)"
  	  replacement = "https://admin.example.com/"
  	  permanent = true
    [frontends.webmin.routes.1]
      rule = "Host:admin.example.com"
```

2)
```toml
#webmin
  [frontends.webmin]
    backend = "webmin"
    entryPoints = ["http", "https"]
    passHostHeader = false
	[frontends.webmin.whiteList]
	  sourceRange = ["192.168.255.0/24", "10.8.0.0/24"]
	  useXForwardedFor = true
	[frontends.webmin.headers]
	  forceSTSHeader = true
	  STSSeconds = 315360000
	  STSIncludeSubdomains=true
	  STSPreload = true
    [frontends.webmin.redirect]
  	  regex = "^https?://127.0.0.1:10000/(.*)"
  	  replacement = "https://admin.example.com/"
  	  permanent = true
    [frontends.webmin.routes.1]
      rule = "Host:admin.example.com"
```
