### ISSUE TITLE
Webmin broke the whole network on the server

### ISSUE THREAD

**Issue by thescs** [webmin/webmin#1546]
Yesterday I introduced the port forwarding rule into the firewall, after which my network completely fell off.
After connecting to the server through a monitor with a keyboard, I found out that both network interfaces stopped automatically turning on.
In addition, the statics settings of one interface have disappeared.
I manually restored the settings via Webmin, rebooted the server and ran into the same problem again.
When I tried to execute the command "sudo netplan try" I got a mismatched indentation error.
It was in the file _/etc/netplan/01-netcfg.yaml_

```
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: yes
        enp2s6:
             addresses: ['192.168.0.1/24']
             nameservers:
                 addresses: [8.8.8.8, 8.8.4.4]


```

I fixed the indentation and the rules applied successfully.

But besides this, traffic from the external network to the internal one has ceased to be routed, although the firewall settings have not changed.

there are no errors or failures in the system logs.

**Comment by jcameron** [comment]
Can you attach your netplan file before Webmin corrupted it (or after you fixed it) to this bug report?

**Comment by thescs** [comment]
```
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: yes
    enp2s6:
      addresses: ['192.168.0.1/24']
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
```

This is the current configuration. The previous one is gone.There is also a problem with the network crashing every ≈1 hour. I added the command to the crontab for every hour "netplan apply".  After executing this command, the network is working normally. But the problem with regular network crashes remains, and I cannot understand why.
