### ISSUE TITLE
Dark Mode graphical issue in System Log Viewer

### ISSUE THREAD

**Issue by itsTheFae** [webmin/webmin#2049]
While using Chromium (version 119.0.6045.159 at time of post) to access a webmin server where the UI is set to Dark Mode, I have noticed an issue with the System Log Viewer while filtering log files. 
When filtering log file lines in dark-mode, the lines appear to overlap or otherwise jumble up. 

Webmin version:   2.105
Authentic theme version:   21.09.5 

A quick CSS hack using the inspector points me to the following CSS rule:
```css
html[data-bgs='nightRider'] .cm-s-monokai span {
    -webkit-filter: hue-rotate(-4deg);
    filter: hue-rotate(-4deg);
}
```

Adding `display: contents;` to this rule appears to fix the issue.  Though I have not tested this outside of my inspector or in a non-chrome-like browser.  I recall some shenanigans with these types of filters and Mozilla, but its been a while and I'm pretty dull.  Suffice to say I expect someone with better working knowledge of the theme can maybe use this info to come up with a better fix than me.  Hope it helps anyway.
