### ISSUE TITLE
Webmin on Ubuntu Server 18.04LTS: Network settings not working with Netplan

### ISSUE THREAD

**Issue by extremeskillz** [webmin/webmin#930]
Ubuntu uses Netplan on server side now since 17.10 I believe and I am having issues with Webmin not able to edit my network configs and keeping them. The active on boot window is where I put my static config in and when I apply the network changes it does not apply to the Active now side. No change after a reboot as well. This is definitely a bug. This worked fine on Ubuntu 14.04lts. This limits my upgrade process to the latests OS since I use Webmin on all Ubuntu servers for a GUI.

**Comment by jcameron** [comment]
Known issue, which is being actively worked on.

**Comment by Sopor-** [comment]
```
# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown
```

**Comment by extremeskillz** [comment]
I saw that but I wanted to state the bug with webmin using netplan since that is the way Ubuntu is going so Webmin can work with Netplan if that is the plan to support support future version of the OS's. Webmin  current work as it should on Ubuntu 16.04lts. I hope the support for 18.04LTS comes in the near future.

**Comment by gametimesav** [comment]
Still not love ... I didn't even know about this till now. Was doing a fresh install, and went to setup the firewall. Then started looking at my main server and seen it was a problem also. Beem kinda looking around for a few days for whats up. Didn't know at first if it was something i did or what ... Happy to see it is a problem ... lol ... Please fix this ... Webmin has always worked great on ubuntu ...

**Comment by rostovtsev** [comment]
@gametimesav What is the Webmin version that you have installed, where it's still not working?

**Comment by gametimesav** [comment]
The networking part ... Non of the firewall settings work
*Operating system* Ubuntu Linux 18.04
*Webmin version* 1.890
*Theme version* Authentic Theme
<https://github.com/authentic-theme/authentic-theme> 19.19

**Comment by gametimesav** [comment]
*Rules file /etc/ip6tables.up.rules*
 HTTP/1.0 500 Perl execution failed Server: MiniServ/1.890 Date: Fri, 20
Jul 2018 13:41:31 GMT Content-type: text/html; Charset=iso-8859-1
Connection: closeError - Perl execution failed

Undefined subroutine &net::get_interface_defs called at debian-linux-lib.pl
line 63.

**Comment by p-schneider** [comment]
In Version 1.890 webmin is not able to properly parse `addresses: [123.123.123.123/29, "1234:1234:1234:1234::1:2/112"]` in `/etc/netplan/*.yaml` but without double or single quotes it wouldn't be valid yaml so the netplan wouln't be able to parse what webmin would use.
(Using static IPv6 setup on Ubuntu 18.04)

**Comment by jcameron** [comment]
The firewall issue should be fixed with this commit : https://github.com/webmin/webmin/commit/e0621384a9da116b1898ea4365a659bc82df9f6b

**Comment by jcameron** [comment]
Also, just checked in a couple of fixes for the quoted addresses.

**Comment by p-schneider** [comment]
Is there already a .deb we can use to test the fixes provided in the latest commits?
(I saw that the `last modified` changed for the files in https://download.webmin.com/devel/deb/ but the version stayed at 1.890 and the [1.890 tag](https://github.com/webmin/webmin/releases/tag/1.890) is 6 commits behind master so i assume the `last modified` just came from some cron job last night that just reuploaded the same files.)

**Comment by jcameron** [comment]
There's no .deb with the fixes yet, but they will be in 1.891.

**Comment by extremeskillz** [comment]
Looks like there is progress on this. I will be firing up a fresh 18.04LTS server VM to test 1.891 when it is released. For now we kept our latest servers on Ubuntu 16.04lts with webmin 1.890 and they are fine and configure as they should with Webmin.

**Comment by gametimesav** [comment]
Networking firewall was working in beta-1 theme .. IDK ... then in beta-2
it stopped again ... however, read user mail is working now ...
Just did a full update today .... FYI

**Comment by jcameron** [comment]
Have you tried Webmin 1.891 from http://www.webmin.com/devel.html ? It fixes some of these Ubuntu 18 issues.

**Comment by gametimesav** [comment]
No .. always used apt to install it ..... sarge contrib  ... how or can i
cant it here to the dev version? and how?

**Comment by p-schneider** [comment]
```sh
wget https://download.webmin.com/devel/deb/webmin_current.deb
sudo dpkg -i webmin_current.deb
```
For me it still doesn't fully work in 1.891, it still looks like this: (see my comment from 20 days ago)
![webmin-ipv6-netplan](https://user-images.githubusercontent.com/2636101/43012592-cc0752ae-8c46-11e8-9f74-a2c641fa3a80.png)

**Comment by jcameron** [comment]
Ok, turns out there is a separate bug that is causing this :-(

It is fixed by this patch though : https://github.com/webmin/webmin/commit/c24070ff0cd8e1713bb43f102117a888d1633da6

**Comment by extremeskillz** [comment]
Just found out the recent release is causing issues on Ubuntu 16.04LTS network settings as well. What is happening is what is going on with 18.04lts. So same symptom. You update the network settings from DHCP to static, save and apply, and nothing happens. 16.04lts does not use Netplan. Only 17.10 and forward. So right now there is the same issues with two OS releases. I wanted to let you know.

**Comment by p-schneider** [comment]
> Ok, turns out there is a separate bug that is causing this :-(
> 
> It is fixed by this patch though : c24070f

Even with that patch (patched manually on top of a 1.891 install) the ipv6 address is still interpreted as IPv4 instead of being listed in the IPv6-address column.

**Comment by extremeskillz** [comment]
Thanks for the update. Right now I configured my latest 16.04LTS releaseses manually and that is holding and being interpeted by webmin if you view it but don't make changes. Skipping 18.04LTS for now.

**Comment by jcameron** [comment]
@swelljoe - you might want to try the latest checked-in code and see if that helps. I will build a 1.894 devel version this week once I get my regular devel environment back online.

**Comment by swelljoe** [comment]
I looked and didn't see any networking related commits since 1.893 was tagged. But, I'll give it a poke just in case.

**Comment by jcameron** [comment]
There are some fixes here : https://github.com/webmin/webmin/commits/master/net/netplan-lib.pl

I *think* they fix the problem with addresses being duplicated, but I will build a new 1.894 devel version to test with on your droplet (if it's still up).

**Comment by swelljoe** [comment]
Nope, it's still slurping the name servers into interfaces, and repeating interface addresses.

**Comment by marcelmah** [comment]
Would like to have this fixed to (can't program unfortunately), hate defining fixed IP's in text config files.

**Comment by bobinson** [comment]
much needed fix ...

**Comment by swelljoe** [comment]
Can y'all poke at Webmin 1.900 and see if the problems you had have been resolved? Jamie thinks it's all been sorted out, but testing might shake out more problems or unsupported syntax.

**Comment by swelljoe** [comment]
Nope, still borked, but in new ways.

Here's an example of a botched config with 1.900:

```
network:
  version: 2
  renderer: networkd
  ethernets:
        eth0:
            addresses: ['/32']
            nameservers:
                addresses: [127.0.0.1,127.0.0.53]
                search: [invalid]
            match:
                macaddress: 23:05:44:46:6d:5a
        macaddress: 23:05:44:46:6d:5a
      addresses:
        - 176.249.10.180/24
        - 2a35:c233:0000:1358:0000:0000:0000:0001/64
      gateway4: 176.249.10.1
      gateway6: fe80::1
      nameservers:
        search: [ invalid ]
        addresses:
          - 8.8.8.8
          - 8.8.4.4
          - 2a35:c233::2:53
          - 2a99:c237::1:53
```

**Comment by swelljoe** [comment]
The things that I think(?) are wrong:

  - Moved interface eth0 addresses value (176.249.10.1, and the IPv6 one) out into a standalone addresses section. Left an empty-ish ['/32'] in the eth0 section.
  - Got the search field wrong (not sure what it was supposed to be on this system, but invalid obviously aint it).
  - eth0 doesn't actually exist on this system...so, I'm not sure what's going on there. it's actually named enp1s0. This may, or may not, be Webmin's doing. Maybe there's a magical alias feature or something that I don't understand and eth0 can be used. I cleaned it up as best I could, so the customer could get to work, but I'll see if I can reproduce this kind of problem on one of our servers, so we can break it at will.

**Comment by jcameron** [comment]
I'd be really interested to see what the config looked like before the corruption!

Also, was this triggered by some action in the Webmin UI, or when the internal API to edit an interface was called by some other script?

**Comment by swelljoe** [comment]
I wish I'd made a backup. I can't seem to reproduce it on other servers that I can tinker with. I've tried on both a Vultr and Digital Ocean VM and while both are now using netplan configs, by default, the installer works successfully and doesn't destroy the configuration, as far as I can tell.

I'll keep an eye out for other folks with problems, but I think we're doing the right thing most of the time. Maybe just a specific kind of YAML trips up the parser. I don't know if it's interesting/useful or not, but when I did the install, the Networking configuration step failed the first time, but then succeeded when I ran it again...so, I think Webmin re-wrote the config in a form that it would be happy with, and when it read it the next time didn't choke on it. (Of course, what it wrote was broken.)

**Comment by marcelmah** [comment]
I just build a new VM based on Ubuntu 18.04 (mini.iso) to test this.

Installed Webmin (1900) and tested basic configuration (just change DHCP to fixed IP).
Config looked fine, reboot also returned the VM in a working state. So basic functionality looks to be ok.

**Comment by cengbrecht** [comment]
I have rebuilt my Unifi Controller 3 times now because of this. :P I can replicate it everytime.

Need some test data?

**Comment by extremeskillz** [comment]
Looks like 1900 is released so I will try it and leave feed back accordingly.

**Comment by swelljoe** [comment]
@cengbrecht yes, if you could paste in the original config (the files in /etc/netplan) and the config that Webmin generates so we can see in what way it is breaking things, that would be extremely helpful.

**Comment by cengbrecht** [comment]
@swelljoe 
Here is before. :) 
This is a temp server:
![image](https://user-images.githubusercontent.com/1149435/49059398-fa00ae00-f1c5-11e8-940a-57b1e373fd33.png)

**Comment by cengbrecht** [comment]
@swelljoe 
After fresh install of Webmin:
![image](https://user-images.githubusercontent.com/1149435/49059483-76938c80-f1c6-11e8-9409-653c6466fd8d.png)

**Comment by cengbrecht** [comment]
@swelljoe 
Sorry, forgot to install webmin. :P 
There was no change immediately after install. :) 
However, after adding 9.9.9.9 to the dns list in the network config:
![image](https://user-images.githubusercontent.com/1149435/49059646-1d782880-f1c7-11e8-8339-a07b829683ae.png)

**Comment by cengbrecht** [comment]
Before netplan Apply:
![image](https://user-images.githubusercontent.com/1149435/49059665-2f59cb80-f1c7-11e8-914f-707f441d409b.png)
No change after apply. 
Rebooting.

**Comment by cengbrecht** [comment]
It would seem that Netplan is not broken on a fresh install. 
![image](https://user-images.githubusercontent.com/1149435/49059726-734cd080-f1c7-11e8-9f3d-cd2940acc68b.png)

**Comment by cengbrecht** [comment]
@swelljoe 
I am going to add more nic's and ipv6. I only have ipv4 enabled, and no local networking.

**Comment by swelljoe** [comment]
It looks like things worked OK...I don't see anything "wrong" with the config Webmin generated. It's differently formatted (and maybe it'd be ideal if it retained the style), but either is valid YAML and looks like legit config.

When posting config files like this, I just use three backticks to open and close the code block. It worked fine for me above for these YAML files.

Anyway, I think we're stuck in a holding pattern until we can find a config that breaks. I know it *does* break in some circumstances, because I've seen it myself but it was on a client box that I couldn't really break at will, and I didn't have a backup of the original config, and once I cleaned it up Webmin was happy with it. So...

**Comment by jcameron** [comment]
Yeah, if you can find a config that Webmin re-writes incorrectly, please let me know.

**Comment by extremeskillz** [comment]
So as of today, 12/5, Webmin 1.9000 will not setup the static IP still. When you go and do it and apply it just keeps it in DHCP and ignores it. I did check my Netplan files and nothing changed. Still an issue. I wanted to leave some feedback.

**Comment by joeyd** [comment]
> So as of today, 12/5, Webmin 1.9000 will not setup the static IP still. When you go and do it and apply it just keeps it in DHCP and ignores it. I did check my Netplan files and nothing changed. Still an issue. I wanted to leave some feedback. In fact, after a reboot the nic was left down with no config. Had to revert back to DHCP to get it working.

Exact same issue here with 1.9000.

**Comment by joeyd** [comment]
For more claification, I have just done a fresh install of Ubuntu 18.04.1 (Official AWS Provided AMI) and Set a FQDN hostname and installed Virtualmin under VPC. Install of Virtualmin was error free.

1. Login to virtualmin as root, create new virtualhost and assign static private IP. 
2. Went to Webmin > Networking > Network Configuration > Network Interfaces, Interface did get generated from step 1. <img width="1431" alt="before-reboot-" src="https://user-images.githubusercontent.com/2018194/49615112-848d9e00-f97a-11e8-9a89-2dd4ec1e0d88.png">
3. Rebooted server, went to Webmin > Networking > Network Configuration > Network and the interface created above is missing and now reporting a new static IP. <img width="1413" alt="after-reboot" src="https://user-images.githubusercontent.com/2018194/49615157-a7b84d80-f97a-11e8-8c7e-a5737ae6ad67.png">

Here is the 50-cloud-init.yaml with a fresh install
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        ens5:
            dhcp4: true
            nameservers:
                addresses: [127.0.0.1,127.0.0.53]
                search: [ec2.internal]
            match:
                macaddress: 12:52:c6:ec:32:6a
            set-name: ens5
```
Here is the 50-cloud-init.yaml after adding virtual server
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        ens5:
            dhcp4: true
            addresses: ['10.0.3.52/24']
            nameservers:
                addresses: [127.0.0.1,127.0.0.53]
                search: [ec2.internal]
            match:
                macaddress: 12:52:c6:ec:32:6a
            set-name: ens5
```

Here is the 50-cloud-init.yaml after reboot of adding virtual server
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        ens5:
            dhcp4: true
            addresses: ['10.0.3.52/24']
            nameservers:
                addresses: [127.0.0.1,127.0.0.53]
                search: [ec2.internal]
            match:
                macaddress: 12:52:c6:ec:32:6a
            set-name: ens5
```

If there is any other info I can provide, let me know.

**Comment by jcameron** [comment]
There is another bug that prevents switching out of DHCP mode properly, fixed by this patch : https://github.com/webmin/webmin/commit/02ad7654087d92f87ca5bbb6998ac81412df5359#diff-1017cdb95b6200e8b2a979089b5b032c

**Comment by extremeskillz** [comment]
Will that be in the next release?

**Comment by sz00gun** [comment]
Wondering why did @jcameron close the topic? This bug still exists even in 1.910 version.

We urgently need a fix.

Anyone have more info? Tips? Ideas?

**Comment by jcameron** [comment]
@sz00gun - what issue are you seeing exactly?

**Comment by sz00gun** [comment]
@jcameron - on the fresh Ubuntu 18.04 and the latest webmin when you add more IP addresses, in my case fail over IP from ovh. All looks ok in Network manager, however after the reboot, all IP addresses disappear. After that, all websites become unreached too. That's the biggest big ever.

There are few topics on the forum about this... At this moment I upgraded U16.04 and all works fine so far.

**Comment by jcameron** [comment]
@sz00gun - can you post your Netplan config file when this happens?

**Comment by sz00gun** [comment]
@jcameron - for better understanding the issue, I recorded a screen cast. Please have a look
https://screencast-o-matic.com/watch/cqh2qJZWHp

**Comment by joeyd** [comment]
I get the same thing. But in my case, I use virtualmin to create virtual hosts and add the IP addresses there vs. directly on the interface. It all works fine until a reboot happens. In my case, I am on AWS's Ubuntu 18.04 LTS image. Not sure if you have access to AWS or any Ubuntu 18.04 LTS cloud based instance, but seems that with Netplan, the cloud init yaml interface will get overwritten on every reboot  and default to a single IP.

**Comment by jcameron** [comment]
If the YAML file is being over-written on reboot, that isn't something Webmin is doing - rather, its likely part of the AWS image boot process.

**Comment by sz00gun** [comment]
From my observation, either it's not working on ovh dedicated machine, and digital ocean, vultr VPS. 

However, for instance netplan is working fine with Vesta Control Panel...

**Comment by maxfahl** [comment]
I've discovered the following:

1. Start with a clean slate, that is an empty `etc/netplan` directory.
2. Add a new interface under the "Activate on boot" tab.
3. Delete the interface under "Activate on boot".
4. The `etc/netplan/ep1s0.yaml` still exists with the following contents:
```
network:
    ethernets:
```
5. Re-add the configuration for the same interface under "Activate on boot". When finished, `etc/netplan/ep1s0.yaml` will look like this:
```
network:
    ethernets:

network:
    ethernets:
        enp1s0:
            addresses: ['10.0.1.20/24']
```
6. The configuration under "Activate on boot" will no longer be visible since the file is corrupt.

It seems that webmin parses the yaml-file incorrectly when adding a configuration for an interface that has been added before (and then removed). My guess is that webmin doesn't parse the existing structure of network.ethernets to put in the entry for enp1s0.addresses inside of it, but instead creates a new structure. This will mess up the file and make it unparsable, ie. it will not show up under "Activate on boot" anymore.

If you have trouble adding a configuration for an interface that has been added before and then deleted, just delete the file for the interface under `etc/netplan` and add it again.

**Comment by TheWizz** [comment]
Can we please have this issue re-opened. We're seeing the same problem as descibed in the previous posting. So it't clearly not fixed. What information can I provide to help troubleshoot and fix this issue?

-JM

**Comment by jcameron** [comment]
TheWizz - can you post your netplan config files?

**Comment by TheWizz** [comment]
When I start out, /etc/netplan contains only the single file "01-network-manager-all", with the following content:

```
# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
```
This is on a desktop Ubuntu 18.04, with latest updates as of today. So I start by stopping and disabling NetworkManager, as described here:

https://askubuntu.com/questions/1091653/how-do-i-disable-network-manager-permanently

I then delete the above  "01-network-manager-all" file to get NetworkManager out of the picture.

Now, looking at the list of interfaces in Webmin, this is  empty:

![1](https://user-images.githubusercontent.com/4129909/57979510-d4d75480-7a1e-11e9-8d65-0e90c1780d0d.png)

I then proceed adding a new interface, specifying the desired IP address and other details.

![2](https://user-images.githubusercontent.com/4129909/57979534-54652380-7a1f-11e9-9927-adf31592cec6.png)

The resulting enp0s10.yaml file contains 

```
network:
    ethernets:
        enp0s10:
            addresses: ['192.168.0.22/24']
```

All well and good so far. I now DELETE the interface I just added. This works OK, but LEAVES the file enp0s10.yaml in place, wth the following content:

```
network:
    ethernets:
```

This seems to do no harm, but sets the trap for the final step. I now re-add that same interface again, with the following settings:

![4](https://user-images.githubusercontent.com/4129909/57979568-ed943a00-7a1f-11e9-9197-b3f80b8866a2.png)

This results in the following INCORRECT content of the enp0s10.yaml file:

```
network:
    ethernets:
network:
    ethernets:
        enp0s10:
            addresses: ['192.168.0.22/24']
```

As you see, this results in an invalud YAML file. This is not recognized by webmin (shows no entries in the list of NICs), nor by netplan itself.

The fix is to manually delete the leftover lines in the enp0s10.yaml file, so it now looks like this:

```
network:
    ethernets:
        enp0s10:
            addresses: ['192.168.0.22/24']
``` 

This now appears properly in webmin's NIC list, and works as expected with netplan.

So it seems the solution would involve either of the following:

1. When deleting an interface, also delete its corresponding netplan file.
2. When adding a NIC, append that under any already existing "network:ethernets:" section in the YAML file, rather than appending a new such section.

-JM
